---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    '': 'App\Controllers\PhotoboxController'
    'photobox': 'App\Controllers\PhotoboxController'
    'photobox//$Action': 'App\Controllers\PhotoboxController'
    'photolist//$Action': 'App\Controllers\PhotolistController'
    'capture//$Action': 'App\Controllers\PhotoboxController'
    'person-selection//$Action': 'App\Controllers\PhotoboxController'
    'success//$Action': 'App\Controllers\PhotoboxController'
    'download/$Hash': 'App\Controllers\PhotoDownloadController'
    'api//$Action//$ID/$Name': 'App\Controllers\ApiController'
